import { Routes } from '@angular/router';
import { HomePage } from './pages/home/home.page';
import { ProductListPage } from './pages/product-list/product-list.page';
import { ProductDetailsPage } from './pages/product-details/product-details.page';
import { CartPage } from './pages/cart/cart.page';
import { CheckoutPage } from './pages/checkout/checkout.page';
import { ProfilePage } from './pages/profile/profile.page';
import { LoginPage } from './pages/login/login.page';
import { RegisterPage } from './pages/register/register.page';
import { WishlistPage } from './pages/wishlist/wishlist.page';
import { AdminDashboardPage } from './pages/admin-dashboard/admin-dashboard.page';
import { AdminProductsPage } from './pages/admin-products/admin-products.page';
import { AdminProductFormPage } from './pages/admin-product-form/admin-product-form.page';

export const appRoutes: Routes = [
  { path: '', component: HomePage },
  { path: 'products/admin', component: AdminProductsPage },
  { path: 'products', component: ProductListPage },
  { path: 'products/:id', component: ProductDetailsPage },
  { path: 'cart', component: CartPage },
  { path: 'checkout', component: CheckoutPage },
  { path: 'profile', component: ProfilePage },
  { path: 'login', component: LoginPage },
  { path: 'register', component: RegisterPage },
  { path: 'wishlist', component: WishlistPage },
  { path: 'admin', component: AdminDashboardPage },
  { path: 'admin-product-form', component: AdminProductFormPage },
  { path: '**', redirectTo: '' }
];
